name: Deploy to Minikube
on:
  push:
    branches:
      - 05-setup-github-workflow 
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to minikube in Github Actions!
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster
      run: kubectl get pods -A
    - name: Setup Docker environment
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
    - name: Print current app version
      run: |
        echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
        echo "Current version: ${{ env.current_version }}"
    - name: Generate Modified Deployment YAML
      run: |
        sed -e "s/microservice1:1.0.0/microservice1:${{ env.current_version }}/g" deployment-service1.yaml > modified-deployment-service1.yaml
        sed -e "s/microservice2:1.0.0/microservice1:${{ env.current_version }}/g" deployment-service2.yaml > modified-deployment-service2.yaml
    - name: Build microservice1 image
      run: docker build -f ./service1/Dockerfile -t microservice1:${{ env.current_version }} ./service1
    - name: Build microservice2 image
      run: docker build -f ./service2/Dockerfile -t microservice2:${{ env.current_version }} ./service2
    - name: Print docker images
      run: docker images 
    - name: Deploy to minikube
      run: |
        kubectl apply -f modified-deployment-service1.yaml
        kubectl apply -f modified-deployment-service2.yaml
        kubectl apply -f service-service1.yaml
        kubectl apply -f service-service2.yaml
    - name: List deployments
      run: kubectl get deploy
    - name: List services
      run: kubectl get service
    - name: List pods
      run: kubectl get pods
    - name: Get pod name
      id: pod
      run: |
        # Get the name of a pod (replace the logic here with your selection criteria)
        POD_NAME=$(kubectl get pods -o jsonpath='{.items[0].metadata.name}')
        echo "Selected pod name: $POD_NAME"
        
        # Set the pod name as an output variable
        echo "::set-output name=pod_name::$POD_NAME"
        
    - name: Describe selected pod
      run: |
        # Get the pod name from the output variable
        POD_NAME=${{ steps.pod.outputs.pod_name }}
        
        # Describe the selected pod
        kubectl describe pod "$POD_NAME"

    - name: Test service URLs
      run: |
        minikube service list
        minikube service service2-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service service2-service --url)        
