name: Deploy to Minikube
on:
  push:
    branches:
      - 05-setup-github-workflow 
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to minikube in Github Actions!
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster
      run: kubectl get pods -A
    - name: Print current app version
      run: |
        echo "current_version=$(grep '# version' version.md | cut -d ' ' -f3)" >> $GITHUB_ENV
        echo "Current version: ${{ env.current_version }}"
    - name: Setup Docker environment
      run: eval $(minikube -p minikube docker-env)
    - name: Build microservice1 image
      run: docker build -f ./service1/Dockerfile -t microservice1:${{ env.current_version }} ./service1
    - name: Build microservice2 image
      run: docker build -f ./service2/Dockerfile -t microservice2:${{ env.current_version }} ./service2
    - name: Print docker images
      run: docker images 
    - name: Deploy to minikube
      run: |
        kubectl apply -f deployment-service1.yaml
        kubectl apply -f deployment-service2.yaml
        kubectl apply -f service-service1.yaml
        kubectl apply -f service-service2.yaml
    - name: List deployments
      run: kubectl get deploy
    - name: List services
      run: kubectl get service
    - name: List pods
      run: kubectl get pods
    - name: Test service URLs
      run: |
        minikube service list
        minikube service service2-service --url
        echo "------------------opening the service------------------"
        curl $(minikube service service2-service --url)        
